name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Linux repo
        uses: actions/checkout@v2
        with:
          path: ./linux

      - name: Checkout RajSDE repo
        uses: actions/checkout@v2
        with:
          repository: RajSDE/RajSDE
          path: ./raj_sde

      - name: List directory contents for debugging
        run: |
          echo "Linux repo contents:"
          ls -la ./linux
          echo "RajSDE repo contents:"
          ls -la ./raj_sde

      - name: Fetch external README from RajSDE
        run: |
          cp ./raj_sde/Readme.md ./external_readme.md

      - name: Compare README files
        id: check_readme
        run: |
          if cmp -s ./external_readme.md ./linux/README.md; then
            echo "README files are identical"
            echo "::set-output name=changed::false"
          else
            echo "README files are different"
            echo "::set-output name=changed::true"
        shell: bash

      - name: Update Linux README if changed
        if: steps.check_readme.outputs.changed == 'true'
        run: |
          cat external_readme.md > ./linux/README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd ./linux
          git add README.md
          git commit -m "Updated README with external content"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/RajSDE/Linux.git
