name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'  # Runs daily

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Linux repo
        uses: actions/checkout@v2
        with:
          path: ./linux  # Checkout into a directory

      - name: Checkout RajSDE repo
        uses: actions/checkout@v2
        with:
          repository: RajSDE/RajSDE
          path: ./raj_sde  # Checkout into a different directory

      - name: List directory contents for debugging
        run: |
          echo "Linux repo contents:"
          ls -la ./linux
          echo "RajSDE repo contents:"
          ls -la ./raj_sde

      - name: Fetch external README from RajSDE
        run: |
          cp ./raj_sde/Readme.md ./external_readme.md

      - name: Append external README to Linux README
        run: |
          cat external_readme.md >> ./linux/README.md
          git config --global user.name "RajSDE"
          git config --global user.email "ayerajkumar@gmail.com"
          cd ./linux
          git add README.md
          git commit -m "Updated README with external content"
          git push
