name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'  # Runs daily

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Linux repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure the entire history is fetched

      - name: List directory contents for debugging
        run: ls -la

      - name: Fetch external README from RajSDE
        run: |
          curl -o external_readme.md https://raw.githubusercontent.com/RajSDE/RajSDE/master/Readme.md

      - name: Append external README to Linux README
        run: |
          cat external_readme.md >> ./Linux/README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./Linux/README.md
          git commit -m "Updated README with external content"
          git push
